hospital-project/Controllers/ClinicController.cs
using hospital_project.Interfaces;
using hospital_project.Models;
using hospital_project.Repository;
using hospital_project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace hospital_project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ClinicController : Controller
    {
        private readonly IClinicRepository _clinicRepository;
        private readonly IHospitalRepository _hospitalRepository;
        private readonly IHospitalClinicRepository _hospitalClinicRepository;

        public ClinicController(IClinicRepository clinicRepository, IHospitalRepository hospitalRepository, 
            IHospitalClinicRepository hospitalClinicRepository)
        {
            _clinicRepository = clinicRepository;
            _hospitalRepository = hospitalRepository;
            _hospitalClinicRepository = hospitalClinicRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Clinic clinic)
        {
            if (!ModelState.IsValid)
            {
                return View(clinic);
            }
            _clinicRepository.Add(clinic);
            return RedirectToAction("Index");
        }

        
        public IActionResult ClinicHospitalMatch()
        {
            var clinicVM = new ClinicViewModel();

            clinicVM.Hospitals = _hospitalRepository.GetAllHospitals();
            clinicVM.Clinics = _clinicRepository.GetAllClinics();

            return View(clinicVM);
        }

        [HttpPost]
        public async Task<IActionResult> ClinicHospitalMatch(ClinicViewModel clinicVM)
        {
            if(ModelState.IsValid)
            {
                Clinic clinic = _clinicRepository.GetClinicById(clinicVM.SelectedClinicId);
                Hospital hospital = _hospitalRepository.GetHospitalById(clinicVM.SelectedHospitalId);

                if (clinic == null || hospital == null)
                {
                    return NotFound();
                }


                if (clinic.HospitalClinics.Any(hc => hc.HospitalId == hospital.Id))
                {
                    return Conflict("Hospital is already associated with the clinic.");
                }

                HospitalClinic hospitalClinic = new HospitalClinic
                {
                    ClinicId = clinic.Id,
                    HospitalId = hospital.Id
                };

                _hospitalClinicRepository.Add(hospitalClinic);
            }

            return View(clinicVM);
        }
    }
}

hospital-project/Controllers/ContactController.cs
using hospital_project.Interfaces;
using hospital_project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Numerics;


public class ContactController : Controller
{
    private readonly IContactRepository _contactRepository;
    public ContactController(IContactRepository contactRepository)
    {
        _contactRepository = contactRepository;
    }



    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }


    [HttpPost]
    public IActionResult Index(Contact contact)
    {
        if(!ModelState.IsValid)
        {
            return View(contact);

        }
        _contactRepository.Add(contact);
        return RedirectToAction("Index");
    }

}

hospital-project/Controllers/DoctorController.cs
using hospital_project.Interfaces;
using hospital_project.Models;
using hospital_project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace hospital_project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DoctorController : Controller
    {
        private readonly IDoctorRepository _doctorRepository;
        private readonly IHospitalRepository _hospitalRepository;

        public DoctorController(IDoctorRepository doctorRepository,IHospitalRepository hospitalRepository)
        {
            _doctorRepository = doctorRepository;
            _hospitalRepository = hospitalRepository;
        }
        public  async Task<IActionResult> Index()
        {
            IEnumerable<Doctor> doctors = await _doctorRepository.GetAll();
            return View(doctors);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Doctor doctor = await _doctorRepository.GetByIdAsync(id);
            return View(doctor);
        }
        
        public  IActionResult Create() {
            var doctorVM = new DoctorViewModel(); 

            doctorVM.Hospitals = _hospitalRepository.GetAllHospitals();

            return View(doctorVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DoctorViewModel doctorVM)
        {
            if (ModelState.IsValid)
            {
                Doctor doctor = new Doctor
                {
                    Name = doctorVM.Name,
                    Email = doctorVM.Email,
                    Appointments = doctorVM.Appointments,
                    Hospital = _hospitalRepository.GetHospitalById(doctorVM.SelectedHospitalId)
                };

                _doctorRepository.Add(doctor);
                return RedirectToAction("Index");

            }
            return View(doctorVM);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Doctor doctor = await _doctorRepository.GetByIdAsync(id);

            DoctorViewModel doctorVM = new DoctorViewModel();
            doctorVM.Name = doctor.Name;
            doctorVM.Email = doctor.Email;
            doctorVM.Hospitals = _hospitalRepository.GetAllHospitals();
            
            return View(doctorVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DoctorViewModel doctorVM)
        {
            
            if (ModelState.IsValid)
            {
                Doctor doctor = _doctorRepository.GetDoctorById(doctorVM.Id);
           
                doctor.Name = doctorVM.Name;
                doctor.Email = doctorVM.Email;
                doctor.Hospital = _hospitalRepository.GetHospitalById(doctorVM.SelectedHospitalId);

                _doctorRepository.Update(doctor);

                return RedirectToAction("Index");
                
            }
            return View(doctorVM);
        }

    }
}

hospital-project/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hospital_project.Data;
using hospital_project.Models;
using hospital_project.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace hospital_project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HospitalController : Controller
    {
        private readonly IHospitalRepository _hospitalRepository;
        public HospitalController(IHospitalRepository hospitalRepository)
        {
            _hospitalRepository = hospitalRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Hospital> hospitals = await _hospitalRepository.GetAll();
            return View(hospitals);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Hospital hospital = await _hospitalRepository.GetByIdAsync(id);
            return View(hospital);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Hospital hospital)
        {
            if (!ModelState.IsValid)
            {
                return View(hospital);
            }
            _hospitalRepository.Add(hospital);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            Hospital hospital = await _hospitalRepository.GetByIdAsync(id);
            return View(hospital);





        }

        [HttpPost]
        public async Task<IActionResult> Edit(Hospital hospital)
        {
            if (!ModelState.IsValid)
            {
                return View(hospital);
            }
            _hospitalRepository.Update(hospital);
            return RedirectToAction("Index");
        }
    }
}

hospital-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hospital_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/hospital_project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">hospital_project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Randevu Oluştur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Create">Doktor Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doktorlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">İletişim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospital" asp-action="Index">Hastane</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospital" asp-action="Create">Hastane Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinic" asp-action="Index">Klinik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinic" asp-action="Create">Klinik Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinic" asp-action="ClinicHospitalMatch">Eşleştir</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Kayıt Ol</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Giriş Yap</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - hospital_project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>